---
# 3.1.1 Ensure IP forwarding is disabled (Scored)

- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when: cis_hostonly
