---
# 3.2.3 Ensure secure ICMP redirects are not accepted (Scored)

- name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored)
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
