---
# 3.2.6 Ensure bogus ICMP responses are ignored (Scored)

- name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored)
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
