---
# 3.3.1 Ensure IPv6 router advertisements are not accepted (Scored)

- name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Scored)
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
