---
# 3.3.2 Ensure IPv6 redirects are not accepted (Scored)

- name: 3.3.2 Ensure IPv6 redirects are not accepted (Scored)
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  with_items:
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects
