---
# 3.4.5 Ensure permissions on /etc/hosts.deny are 644 (Scored)

- name: 3.4.5 Ensure permissions on /etc/hosts.deny are 644 (Scored)
  file:
    path: /etc/hosts.deny
    owner: root
    group: root
    mode: 0644
