---
# 3.4.2 Ensure /etc/hosts.allow is configured (Scored)

- name: 3.4.2 Ensure /etc/hosts.allow is configured (Scored)
  lineinfile:
     path: /etc/hosts.allow
     regexp: "^(#)?ALL"
     line: 'ALL: {{ cis_hosts_allow_all_ips | join(", ") }}'
     create: yes
     owner: root
     group: root
     mode: 0644
