---
# 3.5.4 Ensure TIPC is disabled (Not Scored)

- name: 3.5.4 - Check if CIS modprobe configuration exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_3_5_4

- name: 3.5.4 - Check if TIPC is disabled
  command: modprobe -n -v tipc
  register: mod_tipc
  changed_when: mod_tipc.stdout is search('tipc')
  check_mode: false
  failed_when: mod_tipc.rc not in (0,1)

- name: 3.5.4 - Check if TIPC is loaded
  command: lsmod
  check_mode: false
  register: lsmod
  changed_when: lsmod.stdout is search('tipc')

- name: Unload TIPC if required
  command: modprobe -r tipc
  register: mod_tipc_remove
  changed_when: mod_tipc_remove.rc == 0
  when: lsmod.stdout is search('tipc.*')

- name: 3.5.4 Ensure TIPC is disabled (Not Scored)
  lineinfile: 
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install tipc" 
    line: "install tipc /bin/true" 
  when: modprobe_3_5_4.stat.exists is defined and modprobe_3_5_4.stat.exists
