---
# 3.6.2 Ensure default deny firewall policy

- name: 3.6.2 Disable firewalld
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no
    masked: yes
  register: firewalld_systemd_output
  failed_when: firewalld_systemd_output.msg is defined and "Could not find" not in ntalk_systemd_output.msg and "not found on host" not in ntalk_systemd_output.msg
  when: cis_firewall_default_policy == true

- name: 3.6.2 Set default policy to ACCEPT
  command: /sbin/iptables -P {{ item }} ACCEPT
  when: firewalld_systemd_output.changed and
        cis_firewall_default_policy == true
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  register: accept
  tags:
    - "3.6.4"

- name: 3.6.2 CleanUP iptables configuration
  command: /sbin/iptables "{{ item }}"
  with_items:
    - "--flush"
    - "--delete-chain"
    - "--zero"
  when: cis_firewall_default_policy == true and accept is changed
  register: flush

- name: 3.6.2 Enable SSH access
  iptables:
     chain: INPUT
     ctstate: NEW
     destination_port: 22
     protocol: tcp
     jump: ACCEPT
  when: cis_firewall_default_policy == true and flush is changed

- name: 3.6.4 Ensure outbound and established connections are configured (Not Scored)
  iptables:
     chain: INPUT
     ctstate: ESTABLISHED,RELATED
     jump: ACCEPT
  when: cis_firewall_default_policy == true and flush is changed
  tags:
    - "3.6.2"

- name:  3.6.4 Ensure outbound and established connections are configured (Not Scored)
  iptables:
     chain: OUTPUT
     ctstate: NEW,ESTABLISHED
     jump: ACCEPT
  when: cis_firewall_default_policy == true and flush is changed
  tags:
    - "3.6.2"

- name: 3.6.2 Ensure default deny firewall policy (Scored)
  command: /sbin/iptables -P {{ item }} DROP
  when: cis_firewall_default_policy == true and flush is changed
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  tags:
    - "3.6.4"
  register: fw

- name: 3.6.2 Save configuration
  shell: /sbin/iptables-save > /etc/sysconfig/iptables
  notify: restart iptables
  when: fw is changed
  tags:
    - "3.6.4"

- name: 3.6.2 Enabled and start iptables
  systemd:
    name: iptables.service
    state: restarted
    enabled: yes
  when: fw is changed
  tags:
    - "3.6.4"
