---
# 3.6.3 Ensure loopback traffic is configured (Scored)

- name: 3.6.3 Ensure loopback traffic is configured (Scored)
  iptables:
    chain: INPUT
    in_interface: lo0
    jump: DROP
  when: cis_firewall_default_policy == true

- name: 3.6.3 Ensure loopback traffic is configured (Scored)
  iptables:
    chain: OUTPUT
    out_interface: lo0 
    jump: ACCEPT
  when: cis_firewall_default_policy == true

- name: 3.6.3 Ensure loopback traffic is configured (Scored)
  iptables:
    chain: INPUT 
    source: 127.0.0.0/8
    jump: DROP
  when: cis_firewall_default_policy == true
