---
# 3.6.1 Ensure iptables is installed (Scored)

- name: 3.6.1 Ensure iptables is installed (Scored)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "iptables"
    - "iptables-services"
