---
# 1.1.3 Ensure nodev option set on /tmp partition (Scored)
# 1.1.4 Ensure nosuid option set on /tmp partition (Scored) [NOT Separated Partition]
# 1.1.5 Ensure noexec option set on /tmp partition (Scored) [NOT Separated Partition]

- name: 1.1.3 - Ensure nodev option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  with_items: "{{ ansible_mounts | selectattr('mount', 'equalto', '/tmp') | list }}"
  register: tmp_mounted

- name: 1.1.3 - Check if systemd tmp.mount unit-file exists
  stat:
    path: /etc/systemd/system/local-fs.target.wants/tmp.mount
  register: unitfile
  when: not tmp_mounted.changed

- name: "1.1.3 - Ensure nodev option set on /tmp partition\n
         1.1.4 - 1.1.4 Ensure nosuid option set on /tmp partition (Scored)\n
         1.1.5 Ensure noexec option set on /tmp partition (Scored)"
  lineinfile:
    dest: /etc/systemd/system/local-fs.target.wants/tmp.mount
    regexp: "^Options="
    insertafter: "^Type="
    line: "Options=mode=1777,strictatime,noexec,nodev,nosuid"
  when: unitfile.stat.exists and not tmp_mounted.changed
  notify: restart tmp.mount
