---
# 1.1.13 Ensure separate partition exists for /home (Scored)
- name: 1.1.13 Ensure separate partition exists for /home (Scored)
  debug: msg="***Manually create separete /home partition"
  when: "not (ansible_mounts | selectattr('mount', 'equalto', '/home') | list)"
