---
# 1.1.8 Ensure nodev option set on /var/tmp partition (Scored)

- name: 1.1.8 Ensure nodev option set on /var/tmp partition (Scored)
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  with_items: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var/tmp') | list }}"
  register: var_tmp_mount
  tags:
    - level1
    - section1
    - section1_level1
    - "1.1.8"
    - scored
