---
# 1.1.6 Ensure separate partition exists for /var (Scored)

- name: 1.1.6 - Ensure separate partition exists for /var (Scored)
  debug: msg="***Manually create separete /var partition"
  when: "not (ansible_mounts | selectattr('mount', 'equalto', '/var') | list)"
