---
# 1.1.22 Disable Automounting (Scored)

- name: 1.1.22 Disable Automounting (Scored)
  systemd:
    name: autofs
    state: stopped
    enabled: false
  register: autofs_systemd_output
  failed_when: autofs_systemd_output.msg is defined and "Could not find" not in autofs_systemd_output.msg and "not found on host" not in autofs_systemd_output.msg
