---
# 1.1.14 Ensure nodev option set on /home partition (Scored)

- name: 1.1.14 Ensure nodev option set on /home partition (Scored)
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['nodev']) | join(',') }}"
  with_items: "{{ ansible_mounts | selectattr('mount', 'equalto', '/var/tmp') | list }}"
