---
# 1.1.2 Ensure separate partition exists for /tmp (Scored)

- name: 1.1.2 Ensure separate partition exists for /tmp (Scored)
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started
  when: "not (ansible_mounts | selectattr('mount', 'equalto', '/tmp') | list)"
