---
# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
- name: 1.1.7 Ensure separate partition exists for /var/tmp (Scored)
  debug: msg="***Manually create separete /var/tmp partition"
  when: "not (ansible_mounts | selectattr('mount', 'equalto', '/var/tmp') | list)"
