---
# 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
- name: 1.1.12 Ensure separate partition exists for /var/log/audit (Scored)
  debug: msg="***Manually create separete /var/log/audit partition"
  when: "not (ansible_mounts | selectattr('mount', 'equalto', '/var/log/audit') | list)"
