---
# 1.2.2 Ensure GPG keys are configured (Not Scored)
# 1.2.3 Ensure gpgcheck is globally activated (Scored)

- name: "1.2.2 - Find yum repository config files"
  command: "find /etc/yum.conf /etc/yum.repos.d/ -type f ( -name '*.repo' -or -name 'yum.conf' )"
  check_mode: false
  changed_when: false
  register: yum_configs

- name: "1.2.2 Ensure GPG keys are configured (Not Scored)\n
         1.2.3 Ensure gpgcheck is globally activated (Scored)"
  replace:
    name: "{{ item }}"
    regexp: "^gpgcheck=0"
    replace: "gpgcheck=1"
  with_items: "{{ yum_configs.stdout_lines }}"
