---
# 1.3.2 Ensure filesystem integrity is regularly checked (Scored)

- name: 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
  cron:
    name: "CIS 1.3.2 - Run aide filesystem integrity check"
    user: "{{ cis_aide_cron_user }}"
    job: "{{ cis_aide_cron_job }}"
    minute: "{{ cis_aide_cron_minute }}"
    hour: "{{ cis_aide_cron_hour }}"
    weekday: "{{ cis_aide_cron_dow }}"
    day: "{{ cis_aide_cron_dom }}"
    month: "{{ cis_aide_cron_month }}"
    state: present
