---
# 1.5.1 Ensure core dumps are restricted (Scored)

- name: 1.5.1 Ensure core dumps are restricted limits (Scored)
  template:
    src: etc/security/limits.d/CIS-limits.conf.j2
    dest: /etc/security/limits.d/CIS-limits.conf
    owner: root
    group: root
    mode: 0644

- name: 1.5.1 Ensure core dumps are restricted sysctl (Scored)
  sysctl:
    name: fs.suid_dumpable
    value: 0
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
