---
# 1.5.3 Ensure address space layout randomization (ASLR) is enabled (Scored)

- name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled (Scored)
  sysctl:
    name: kernel.randomize_va_space
    value: 2
    state: present
    reload: yes
