---
# 1.6.1.2 Ensure the SELinux state is enforcing (Scored)

- name: Custom Selinux 1.6.1.2 broken
  selinux:
    conf: /etc/selinux/config
    policy: "{{ cis_selinux_policy }}"
    state: disabled
  when: cis_selinux_disabled
