---
# 1.7.2 Ensure GDM login banner is configured (Scored)

- name: 1.7.2 Check if GDM is installed (Scored)
  stat:
    path: /etc/dconf/profile/gdm
  register: gdm_stat
  check_mode: false

- name: 1.7.2 Ensure GDM login banner is configured (Scored)
  copy:
    src: etc/dconf/profile/gdm
    dest: /etc/dconf/profile/gdm
    owner: root
    group: root
    mode: 0644
  notify: update gdb
  when: gdm_stat.stat.exists

- name: 1.7.2 Ensure GDM login banner is configured (Scored)
  template:
    src: etc/dconf/db/gdm.d/01-banner-message.j2
    dest: /etc/dconf/db/gdm.d/01-banner-message
    owner: root
    group: root
    mode: 0644
  notify: update gdb
  when: gdm_stat.stat.exists
