---
# 1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)

- name: 1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)
  file:
    path: /etc/issue
    owner: root
    group: root
    mode: 0644
