---
# 2.1.6 Ensure tftp server is not enabled (Scored)

- name: 2.1.6 Ensure tftp server is not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - tftp-dgram
    - tftp-stream
  register: tftp_systemd_output
  failed_when: tftp_systemd_output.msg is defined and "Could not find" not in tftp_systemd_output.msg and "not found on host" not in tftp_systemd_output.msg
