---
# 2.1.4 Ensure echo services are not enabled (Scored)

- name: 2.1.4 Ensure echo services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - echo-dgram
    - echo-stream
  register: echo_systemd_output
  failed_when: echo_systemd_output.msg is defined and "Could not find" not in echo_systemd_output.msg and "not found on host" not in echo_systemd_output.msg
