---
# 2.1.1 Ensure chargen services are not enabled (Scored)

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - chargen-dgram
    - chargen-stream
  register: chargen_systemd_output
  failed_when: chargen_systemd_output.msg is defined and "Could not find" not in chargen_systemd_output.msg and "not found on host" not in chargen_systemd_output.msg
