---
# 2.1.7 Ensure xinetd is not enabled (Scored)

- name: 2.1.7 Ensure xinetd is not enabled (Scored)
  systemd:
    name: xinetd
    state: stopped
    enabled: false
  register: xinetd_systemd_output
  failed_when: xinetd_systemd_output.msg is defined and "Could not find" not in xinetd_systemd_output.msg and "not found on host" not in xinetd_systemd_output.msg
