---
# 2.1.7 Ensure xinetd is not enabled (Scored)

- name: 2.1.7 Ensure xinetd is not enabled (Scored)
  systemd:
    name: xinetd
    state: stopped
    enabled: false
  when: xinetd_service_status.stdout == "loaded"
