---
# 2.1.2 Ensure daytime services are not enabled (Scored)

- name: 2.1.2 Ensure daytime services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enable: false
  with_items:
    - daytime-dgram
    - daytime-stream
  register: daytime_systemd_output
  failed_when: daytime_systemd_output.msg is defined and "Could not find" not in daytime_systemd_output.msg and "not found on host" not in daytime_systemd_output.msg
