---
# 2.1.3 Ensure discard services are not enabled (Scored)

- name: 2.1.3 Ensure discard services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enable: false
  with_items:
    - discard-dgram
    - discard-stream
  register: discard_systemd_output
  failed_when: discard_systemd_output.msg is defined and "Could not find" not in discard_systemd_output.msg and "not found on host" not in discard_systemd_output.msg
