---
# 2.1.5 Ensure time services are not enabled (Scored)

- name: 2.1.5 Ensure time services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - time-dgram
    - time-stream
  register: time_systemd_output
  failed_when: time_systemd_output.msg is defined and "Could not find" not in time_systemd_output.msg and "not found on host" not in time_systemd_output.msg
