---
# 2.1.6 Ensure tftp server is not enabled (Scored)

- name: 2.1.6 Ensure tftp server is not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enable: false
  with_items:
    - tftp-dgram
    - tftp-stream
  when: tftp_service_status.changed
