---
# 2.1.1 Ensure chargen services are not enabled (Scored)

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enable: false
  with_items:
    - chargen-dgram
    - chargen-stream
  when: chargen_service_status.changed
