---
# 2.1.4 Ensure echo services are not enabled (Scored)

- name: 2.1.4 Ensure echo services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enable: false
  with_items:
    - echo-dgram
    - echo-stream
  when: echo_service_status.changed
