---
# 2.1.2 Ensure daytime services are not enabled (Scored)

- name: 2.1.2 Ensure daytime services are not enabled (Scored)
  service:
    name: "{{ item }}"
    state: stopped
    enable: false
  with_items:
    - daytime-dgram
    - daytime-stream
  when: daytime_service_status.changed
