---
# 2.2.20 Ensure rsync service is not enabled (Scored)

- name: 2.2.20 Ensure rsync service is not enabled (Scored)
  systemd:
    name: rsyncd
    state: stopped
    enabled: no
  when: cis_rsync_server == false and rsyncd_service_status.stdout == "loaded"
