---
# 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)

- name: 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)
  systemd:
    name: httpd
    state: stopped
    enabled: no
  when: cis_dovecot_server == false and dovecot_service_status.stdout == "loaded"
