---
# 2.2.4 Ensure CUPS is not enabled (Scored)

- name: 2.2.4 Ensure CUPS is not enabled (Scored)
  systemd:
    name: cups
    state: stopped
    enabled: no
  register: cups_systemd_output
  failed_when: cups_systemd_output.msg is defined and "Could not find" not in cups_systemd_output.msg and "not found on host" not in cups_systemd_output.msg
  when: cis_cups_server == false
