---
# 2.2.19 Ensure tftp server is not enabled (Scored)

- name: 2.2.19 Ensure tftp server is not enabled (Scored)
  systemd:
    name: tftp.socket
    state: stopped
    enabled: no
  when: cis_tftp_server == false and tftp_service_status.stdout == "loaded"
