---
# 2.2.18 Ensure telnet server is not enabled (Scored)

- name: 2.2.18 Ensure telnet server is not enabled (Scored)
  systemd:
    name: telnet
    state: stopped
    enabled: no
  when: telnet_service_status.stdout == "loaded"
