---
# 2.2.14 Ensure SNMP Server is not enabled (Scored)

- name: 2.2.14 Ensure SNMP Server is not enabled (Scored)
  systemd:
    name: snmpd
    state: stopped
    enabled: no
  register: snmpd_systemd_output
  failed_when: snmpd_systemd_output.msg is defined and "Could not find" not in snmpd_systemd_output.msg and "not found on host" not in snmpd_systemd_output.msg
  when: cis_snmp_server == false
