---
# 2.2.10 Ensure HTTP server is not enabled (Scored)

- name: 2.2.10 Ensure HTTP server is not enabled (Scored)
  systemd:
    name: httpd
    state: stopped
    enabled: no
  when: cis_http_server == false and httpd_service_status.stdout == "loaded"
