---
# 2.2.20 Ensure rsync service is not enabled (Scored)

- name: 2.2.20 Ensure rsync service is not enabled (Scored)
  systemd:
    name: rsyncd
    state: stopped
    enabled: no
  register: rsync_systemd_output
  failed_when: rsync_systemd_output.msg is defined and "Could not find" not in rsync_systemd_output.msg and "not found on host" not in rsync_systemd_output.msg
  when: cis_rsync_server == false
