---
# 2.2.8 Ensure DNS Server is not enabled (Scored)

- name: 2.2.8 Ensure DNS Server is not enabled (Scored)
  systemd:
    name: named
    state: stopped
    enabled: no
  register: named_systemd_output
  failed_when: named_systemd_output.msg is defined and "Could not find" not in named_systemd_output.msg and "not found on host" not in named_systemd_output.msg
  when: cis_named_server == false
