---
# 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)

- name: 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^(#)?inet_interfaces"
    line: "inet_interfaces = loopback-only"
  when: cis_mail_server == false and postfix_installed.results[1].yumstate == 'installed'
  notify: restart postfix
