---
# 2.2.9 Ensure FTP Server is not enabled (Scored)

- name: 2.2.9 Ensure FTP Server is not enabled (Scored)
  systemd:
    name: vsftpd
    state: stopped
    enabled: no
  register: vsftpd_systemd_output
  failed_when: vsftpd_systemd_output.msg is defined and "Could not find" not in vsftpd_systemd_output.msg and "not found on host" not in vsftpd_systemd_output.msg
  when: cis_ftp_server == false
