---
# 2.2.7 Ensure NFS and RPC are not enabled (Scored)

- name: 2.2.7 Ensure NFS and RPC are not enabled (Scored) - server
  systemd:
    name: nfs
    state: stopped
    enabled: no
  when: cis_nfs_server == false and nfs_service_status.stdout == "loaded"

- name: 2.2.7 Ensure NFS and RPC are not enabled (Scored) - client
  systemd:
    name: nfs
    state: stopped
    enabled: no
  when: cis_rpcbind_server == false and rpcbind_service_status.stdout == "loaded"
