---
# 2.2.14 Ensure SNMP Server is not enabled (Scored)

- name: 2.2.14 Ensure SNMP Server is not enabled (Scored)
  systemd:
    name: snmpd
    state: stopped
    enabled: no
  when: cis_snmp_server == false and snmpd_service_status.stdout == "loaded"
