---
# 2.2.10 Ensure HTTP server is not enabled (Scored)

- name: 2.2.10 Ensure HTTP server is not enabled (Scored)
  systemd:
    name: httpd
    state: stopped
    enabled: no
  register: httpd_systemd_output
  failed_when: httpd_systemd_output.msg is defined and "Could not find" not in httpd_systemd_output.msg and "not found on host" not in httpd_systemd_output.msg
  when: cis_http_server == false
