---
# 2.2.3 Ensure Avahi Server is not enabled (Scored)

- name: 2.2.3 Ensure Avahi Server is not enabled (Scored)
  systemd:
    name: avahi-daemon
    state: stopped
    enabled: no
  register: avahi_systemd_output
  failed_when: avahi_systemd_output.msg is defined and "Could not find" not in avahi_systemd_output.msg and "not found on host" not in avahi_systemd_output.msg
  when: cis_avahi_server == false
