---
# 2.2.1.1 Ensure time synchronization is in use (Not Scored)

- name: 2.2.1.1 Ensure time synchronization is in use - service install (Not Scored)
  yum:
    name: ntp
    state: present
  when: cis_enable_ntp

- name: 2.2.1.1 Ensure time synchronization is in use - service start (Not Scored)
  systemd:
    name: ntpd
    state: started
    enabled: yes
  when: cis_enable_ntp

- name: 2.2.1.1 Ensure time synchronization is in use - service stop (Not Scored)
  systemd:
    name: ntpd
    state: stopped
    enabled: no
  register: ntpd_systemd_output
  failed_when: ntpd_systemd_output.msg is defined and "Could not find" not in ntpd_systemd_output.msg and "not found on host" not in ntpd_systemd_output.msg
  when: cis_enable_chrony

- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  yum:
    name: chrony
    state: present
  when: cis_enable_chrony

- name: 2.2.1.1 Ensure time synchronization is in use - service start (Not Scored)
  systemd:
    name: chronyd
    state: started
    enabled: yes
  when: cis_enable_chrony

- name: 2.2.1.1 Ensure time synchronization is in use - service stop (Not Scored)
  systemd:
    name: chronyd
    state: stopped
    enabled: no
  register: chronyd_systemd_output
  failed_when: chronyd_systemd_output.msg is defined and "Could not find" not in chronyd_systemd_output.msg and "not found on host" not in chronyd_systemd_output.msg
  when: cis_enable_ntp
