---
# 2.2.2 Ensure X Window System is not installed (Scored)

- name: 2.2.2 Ensure X Window System is not installed (Scored)
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "@X Window System"
    - "xorg-x11*"
