---
# 2.2.6 Ensure LDAP server is not enabled (Scored)

- name: 2.2.6 Ensure LDAP server is not enabled (Scored)
  systemd:
    name: slapd
    state: stopped
    enabled: no
  register: slapd_systemd_output
  failed_when: slapd_systemd_output.msg is defined and "Could not find" not in slapd_systemd_output.msg and "not found on host" not in slapd_systemd_output.msg
  when: cis_ldap_server == false
