---
# 2.2.5 Ensure DHCP Server is not enabled (Scored)

- name: 2.2.5 Ensure DHCP Server is not enabled (Scored)
  systemd:
    name: dhcpd
    state: stopped
    enabled: no
  register: dhcpd_systemd_output
  failed_when: dhcpd_systemd_output.msg is defined and "Could not find" not in dhcpd_systemd_output.msg and "not found on host" not in dhcpd_systemd_output.msg
  when: cis_dhcp_server == false
