---
# 2.2.7 Ensure NFS and RPC are not enabled (Scored)

- name: 2.2.7 Ensure NFS and RPC are not enabled (Scored) - server
  systemd:
    name: nfs
    state: stopped
    enabled: no
  register: nfs_systemd_output
  failed_when: nfs_systemd_output.msg is defined and "Could not find" not in nfs_systemd_output.msg and "not found on host" not in nfs_systemd_output.msg
  when: cis_nfs_server == false

- name: 2.2.7 Ensure NFS and RPC are not enabled (Scored) - client
  systemd:
    name: rpcbind
    state: stopped
    enabled: no
  register: rpcbind_systemd_output
  failed_when: rpcbind_systemd_output.msg is defined and "Could not find" not in rpcbind_systemd_output.msg and "not found on host" not in rpcbind_systemd_output.msg
  when: cis_rpcbind_server == false
