---
# 2.2.19 Ensure tftp server is not enabled (Scored)

- name: 2.2.19 Ensure tftp server is not enabled (Scored)
  systemd:
    name: tftp.socket
    state: stopped
    enabled: no
  register: tftp_systemd_output
  failed_when: tftp_systemd_output.msg is defined and "Could not find" not in tftp_systemd_output.msg and "not found on host" not in tftp_systemd_output.msg
  when: cis_tftp_server == false
