---
# 2.2.6 Ensure LDAP server is not enabled (Scored)

- name: 2.2.6 Ensure LDAP server is not enabled (Scored)
  systemd:
    name: slapd
    state: stopped
    enabled: no
  when: cis_ldap_server == false and slapd_service_status.stdout == "loaded"
