---
# 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)

- name: 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
  systemd:
    name: squid
    state: stopped
    enabled: no
  register: squid_systemd_output
  failed_when: squid_systemd_output.msg is defined and "Could not find" not in squid_systemd_output.msg and "not found on host" not in squid_systemd_output.msg
  when: cis_squid_server == false
