---
# 2.2.16 Ensure NIS Server is not enabled (Scored)

- name: 2.2.16 Ensure NIS Server is not enabled (Scored)
  systemd:
    name: ypserv
    state: stopped
    enabled: no
  register: ypserv_systemd_output
  failed_when: ypserv_systemd_output.msg is defined and "Could not find" not in ypserv_systemd_output.msg and "not found on host" not in ypserv_systemd_output.msg
  when: cis_nis_server == false
