---
# 2.2.18 Ensure telnet server is not enabled (Scored)

- name: 2.2.18 Ensure telnet server is not enabled (Scored)
  systemd:
    name: telnet
    state: stopped
    enabled: no
  register: telnet_systemd_output
  failed_when: telnet_systemd_output.msg is defined and "Could not find" not in telnet_systemd_output.msg and "not found on host" not in telnet_systemd_output.msg
