---
# 2.2.5 Ensure DHCP Server is not enabled (Scored)

- name: 2.2.5 Ensure DHCP Server is not enabled (Scored)
  systemd:
    name: dhcpd
    state: stopped
    enabled: no
  when: cis_dhcp_server == false and dhcpd_service_status.stdout == "loaded"
