---
# 2.2.1.1 Ensure time synchronization is in use (Not Scored)

- name: 2.2.1.1 Ensure time synchronization is in use - service install (Not Scored)
  yum:
    name: ntp
    state: present
  when: cis_enable_ntp

- name: 2.2.1.1 Ensure time synchronization is in use - service start (Not Scored)
  systemd:
    name: ntpd
    state: started
    enabled: yes
  when: cis_enable_ntp

- name: 2.2.1.1 Ensure time synchronization is in use - service stop (Not Scored)
  systemd:
    name: ntpd
    state: stopped
    enabled: no
  when: cis_enable_chrony and ntpd_service_status.stdout == "loaded"

- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
  yum:
    name: chrony
    state: present
  when: cis_enable_chrony

- name: 2.2.1.1 Ensure time synchronization is in use - service start (Not Scored)
  systemd:
    name: chronyd
    state: started
    enabled: yes
  when: cis_enable_chrony

- name: 2.2.1.1 Ensure time synchronization is in use - service stop (Not Scored)
  systemd:
    name: chronyd
    state: stopped
    enabled: no
  when: cis_enable_ntp and chronyd_service_status.stdout == "loaded"
