---
# 2.2.8 Ensure DNS Server is not enabled (Scored)

- name: 2.2.8 Ensure DNS Server is not enabled (Scored)
  systemd:
    name: named
    state: stopped
    enabled: no
  when: cis_named_server == false and named_service_status.stdout == "loaded"
