---
# 2.2.21 Ensure talk server is not enabled (Scored)

- name: 2.2.21 Ensure talk server is not enabled (Scored)
  systemd:
    name: ntalk
    state: stopped
    enabled: no
  register: ntalk_systemd_output
  failed_when: ntalk_systemd_output.msg is defined and "Could not find" not in ntalk_systemd_output.msg and "not found on host" not in ntalk_systemd_output.msg
  when: cis_ntalk_server == false
