---
# 2.3.5 Ensure LDAP client is not installed (Scored)

- name: 2.3.5 Ensure LDAP client is not installed (Scored)
  yum:
    name: openldap-clients
    state: absent
  when: cis_openldap_clients_required == false
