---
# 4.1.1.1 Ensure audit log storage size is configured (Not Scored)

- name: 4.1.1.1 Ensure audit log storage size is configured (Not Scored)
  lineinfile:
     dest: /etc/audit/auditd.conf
     regexp: "^max_log_file"
     line: "max_log_file = {{ cis_auditd_max_log_size | default(10) }}"
     state: present
